### Create movie
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Interstellar",
  "image": "",
  "description": "",
  "yearReleased": 2014,
  "rating": 2.3,
  "genres": "Fantasy, Adventure",
  "directorId": 1
}

###

### Get movie by ID
GET http://localhost:8080/api/movies/1
Accept: application/json

###

### Update movie
PUT http://localhost:8080/api/movies/1
Content-Type: application/json

{
  "title": "Inception2",
  "yearReleased": 2017,
  "rating": 8.8,
  "directorId": 1
}

###

### Delete movie
DELETE http://localhost:8080/api/movies/1

###

### Movies pagination + filter
POST http://localhost:8080/api/movies/_list
Content-Type: application/json

{
  "directorId": 1,
  "title": "Titanic",
  "yearFrom": 2000,
  "yearTo": 2025,
  "page": 0,
  "size": 20
}

###

### Movies pagination + filter
POST http://localhost:8080/api/movies/_list
Content-Type: application/json

{
"title": "Interstellar",
"page": 0,
"size": 10
}

###

### Movies report
POST http://localhost:8080/api/movies/_report
Content-Type: application/json

{
  "directorId": 1
}

###

### Movies upload
POST http://localhost:8080/api/movies/upload
Content-Type: application/json

[
  {
    "title": "Dunkirk",
    "director": "Christopher Nolan",
    "year": 2017,
    "genres": "War"
  },
  {
    "title": "Kill Bill",
    "director": "Quentin Tarantino",
    "year": 2003,
    "genres": "Action"
  }
]

###

### Get all directors
GET http://localhost:8080/api/directors
Accept: application/json

###

### Create director
POST http://localhost:8080/api/directors
Content-Type: application/json

{
  "name": "Christopher Nolan",
  "country": "United Kingdom"
}

###

### Update director
PUT http://localhost:8080/api/directors/1
Content-Type: application/json

{
  "name": "Christopher Nolan",
  "country": "United Kingdom"
}

###

### Delete director
DELETE http://localhost:8080/api/directors/1
